Repository SleepyLGod/omg-score, pull requests merged in 2022-11, with the labels that each got.

#11 Fix midi generator cli
  OmgPianoTranscription/.gitignore
  OmgPianoTranscription/README.md
  OmgPianoTranscription/pianotranscriptioncli/pom.xml
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/TranscriptionApplication.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/common/api/CommonResult.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/common/api/ErrorCode.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/common/api/ResultCode.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/common/exception/Asserts.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/common/exception/BaseException.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/controller/TranscriptionController.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/dto/Mp3ImportDTO.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/dto/Mp3ImportWithFileDTO.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/service/TranscriptionService.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/service/impl/TranscriptionServiceImpl.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/utils/HttpUtils.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/utils/Utils.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/vo/Mp3ImportVO.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/pianotranscriptioncli/Program.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/pianotranscriptioncli/Utils.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/resources/application.yml
  OmgPianoTranscription/pianotranscriptioncli/src/main/resources/http-client.env.json
  OmgPianoTranscription/pianotranscriptioncli/src/main/resources/output/雨的印记.mid
  OmgPianoTranscription/pianotranscriptioncli/src/main/resources/test.http
  OmgPianoTranscription/pom.xml
Labels: bug, enhancement, question

#14 cross-domain configuration passed
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/TranscriptionApplication.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/config/CorsConfig.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/controller/TranscriptionController.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/resources/test.http
Labels: enhancement, question, java

#20 libs-modified
  OmgPianoTranscription/libpianotranscription/src/main/java/libpianotranscription/midi/MidiWriter.java
  OmgPianoTranscription/libpianotranscription/src/main/java/libpianotranscription/midi/NoteEvent.java
  OmgPianoTranscription/libpianotranscription/src/main/java/libpianotranscription/midi/PedalEvent.java
Labels: documentation, enhancement, question

#22 transcriptor-modified
  OmgPianoTranscription/libpianotranscription/src/main/java/libpianotranscription/Transcriptor.java
Labels: documentation, enhancement, question

#17 Fix midi generator cli
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/controller/TranscriptionController.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/dto/Mp3ImportDTO.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/dto/Mp3ImportWithFileDTO.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/service/TranscriptionService.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/service/impl/TranscriptionServiceImpl.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/utils/MidiUtils.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/java/com/pianotranscriptioncli/utils/Utils.java
  OmgPianoTranscription/pianotranscriptioncli/src/main/resources/demo.http
  OmgPianoTranscription/pianotranscriptioncli/src/main/resources/test.http
Labels: bug, question, java
